[project]
name = "wes-qc"
version = "0.1.0"
description = "QC of human exome cohorts"
readme = "README.md"
requires-python = "~=3.9"
dependencies = [
    "gnomad==0.8.1",
    "hail>=0.2.133",
    "jupyterlab>=3.5.3",
    "onnxruntime<1.20.0 ; python_version <= '3.9'",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
    "pytest-it>=0.1.5",
]
