hard_filters_combinations:
    runhash: fef0f446
    #giab_sample: "EGAN00004265526" # For BiB
    giab_sample: EGAN00003332049 # For ALSPAC
    snp_bins: [36, 40, 42 ]
    indel_bins: [56, 59, 62]
    gq_vals: [10, 15, 20]
    dp_vals: [5, 10]
    ab_vals: [0.2, 0.3]
    missingness_vals: [0, 0.5, 0.9, 0.95]