hard_filters_combinations:
    runhash:
    giab_sample: EGAN00004265526 # For BiB
    snp_bins: [80, 82, 84, 86, 88, 90]
    indel_bins: [58, 60, 62, 64, 66, 68]
    gq_vals: [10, 15, 20]
    dp_vals: [5, 10]
    ab_vals: [0.2, 0.3]
    missingness_vals: [0, 0.5, 0.9, 0.95]