hard_filters_combinations:
    runhash: 5278832e
    #giab_sample: "EGAN00004265526" # For BiB
    #giab_sample: EGAN00003332049 # For ALSPAC
    giab_sample: bibkidex13951069 # For Fenland, taken from here: https://docs.google.com/document/d/1xbDrfBuiAA9Bl8LkF817HHHboxQNeRSS-DozGHH4lro/edit
    snp_bins: [56, 60, 64, 68, 72, 76, 78, 80, 82, 84, 88, 90, 92, 94]
    indel_bins: [48, 52, 56, 58, 60, 64, 66, 68, 70, 72]
    gq_vals: [0, 10]
    dp_vals: [0, 5, 10]
    ab_vals: [0.0, 0.2, 0.3]
    missingness_vals: [0.0, 0.5]
