---
gatk_import_lustre_dir: file:///lustre/scratch126/teams/hgi/ip13/slemap/
annotation_lustre_dir: file:///lustre/scratch126/teams/hgi/ip13/slemap/qc/annotations/
annotation_lustre_dir_local: /lustre/scratch126/teams/hgi/ip13/slemap/qc/annotations/
matrixtables_lustre_dir: file:///lustre/scratch126/teams/hgi/ip13/slemap/qc/matrixtables/
load_matrixtables_lustre_dir: /lustre/scratch126/teams/hgi/ip13/slemap/qc/matrixtables/
plots_lustre_dir: file:///lustre/scratch126/teams/hgi/ip13/slemap/qc/plots/
plots_dir_local: /lustre/scratch126/teams/hgi/ip13/slemap/qc/plots/
resource_dir: file:///lustre/scratch126/teams/hgi/ip13/slemap/resources/
resource_dir_local: /lustre/scratch126/teams/hgi/ip13/slemap/resources/
training_set_dir: file:///lustre/scratch123/qc/BiB/training_sets/
var_qc_rf_dir: file:///lustre/scratch123/qc/BiB/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch123/qc/BiB/filtered_vcfs/

dataset_name: slemap
data_root: /lustre/scratch126/teams/hgi/ip13/slemap/qc/
tmp_dir: "file:///lustre/scratch126/teams/hgi/ip13/slemap/qc/temp/"
kg_pop: igsr_samples.tsv
n_pca: 3

rf_test_interval: chr20

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 92
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 88
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 84
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 68
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 66
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 58
      dp: 5
      gq: 20
      ab: 0.3
