---

general:
  # CVAR tmpdir
  tmp_dir: /lustre/scratch126/mk43/tmp/
  # tmp_dir: hdfs://spark-master:9820/

  # CVAR anndir
  annotation_dir: /lustre/scratch126/dh24_test/qc_test/BiB/annotations/
  
  # CVAR mtdir
  matrixtables_dir: /lustre/scratch126/dh24_test/qc_test/BiB/matrixtables/

  # TODO: document resource_dir
  # TODO: add option to override in `resources` config field
  # TODO: add Jira ticket
  # CVAR resdir
  resource_dir: /lustre/scratch126/dh24_test/qc_test/BiB/resources/

# --- Step 1.1 --- #
step1:
  gatk_vcf_header_infile:
  gatk_vcf_indir: /lustre/scratch126/WES_QC/control_set_vcfs/control_set_small/
  gatk_mt_outfile: {mtdir}/gatk_unprocessed.mt

# --- Step 2.1 --- #
step2:
  sex_annotation_hard_filters:
    filtered_mt_outfile: {mtdir}/mt_hard_filters_annotated.mt
    n_alt_alleles_threshold: 0.001
    defined_gt_frac_threshold: 0.99

  impute_sex:
    sex_ht_outfile: {anndir}/sex_annotated.sex_check.txt.bgz
    sex_mt_outfile: {mtdir}/mt_sex_annotated.mt
    female_threshold: 0.5
    male_threshold: 0.8
    aaf_threshold: 0.05
    
  sex_inconsistencies:
    # TODO: specify structure of a sex metadata file
    sex_metadata_file: {resdir}/mlwh_sample_and_sex.txt
    conflicting_sex_report_path: {anndir}/conflicting_sex.txt.bgz
    fstat_outliers_report_path: {anndir}/sex_annotation_f_stat_outliers.txt.bgz
    fstat_low: 0.2
    fstat_high: 0.8

# unprocessed below this line

plots_lustre_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/plots/
plots_dir_local: /lustre/scratch126/dh24_test/qc_test/BiB/plots/

training_set_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/training_sets/
var_qc_rf_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/filtered_vcfs/

load_matrixtables_lustre_dir: /lustre/scratch126/dh24_test/qc_test/BiB/matrixtables/


rf_test_interval: chr20

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 92
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 88
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 84
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 68
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 66
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 58
      dp: 5
      gq: 20
      ab: 0.3
