---
gatk_vcf_header: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/gatk_vcf_header.txt
gatk_import_lustre_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/
load_matrixtables_lustre_dir: /lustre/scratch125/teams/hgi/ad7/otar2064/qc/matrixtables/
#load_matrixtables_lustre_dir: /lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
annotation_lustre_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/annotations/
annotation_lustre_dir_local: /lustre/scratch125/teams/hgi/ad7/otar2064/qc/annotations/
matrixtables_lustre_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/matrixtables/
matrixtables_local_dir: file:///home/ubuntu/volume/data/
#matrixtables_lustre_dir: file:///lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
plots_lustre_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/plots/
plots_dir_local: /lustre/scratch125/teams/hgi/ad7/otar2064/qc/plots/
resource_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/resources/
resource_dir_local: /lustre/scratch125/teams/hgi/ad7/otar2064/qc/resources/
training_set_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/training_sets/
var_qc_rf_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch125/teams/hgi/ad7/otar2064/qc/filtered_vcfs/20230425/

rf_test_interval: chr20

#hard filter
hard_filters:
  snp:
    relaxed:
      bin: 42
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 40
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 36
      dp: 5
      gq: 20
      ab: 0.2
  indel:
    relaxed:
      bin: 62
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 59
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 56
      dp: 10
      gq: 10
      ab: 0.3
