---

tmp_dir: "hdfs://spark-master:9820/user/ubuntu/hail-tmp"
#tmp_dir: "file:///lustre/scratch123/gz3/tmp"

# === Root folders
data_root: /lustre/scratch126/teams/hgi/gz3-fenland # Root folder for all input and analysis data
dataset_name: gz3-fenland  # Used in automatically created files and folders

gatk_vcf_header: gatk_vcf_header.txt
#gatk_import_lustre_dir: gatk_vcfs_all # All VCFS from Sarek including altcontig on chr1 and mitochondrial chromosome
#gatk_import_lustre_dir:   gatk_vcfs_no_altcontig_no_m # No chr1 altcontig and no M chromosome
#gatk_import_lustre_dir:   gatk_vcfs_test # Ony 1-2 files
gatk_import_lustre_dir:    gatk_vcfs_rmdup


load_matrixtables_lustre_dir: matrixtables  # Writing using direct Python no need the name without file:// prefix
annotation_lustre_dir: annotations
annotation_lustre_dir_local: undefined
matrixtables_lustre_dir: matrixtables
#matrixtables_lustre_dir: file:///lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
stats_dir: stats
plots_lustre_dir: plots
plots_dir_local: plots
resource_dir: resources
resource_dir_local: resources
training_set_dir: training_sets
var_qc_rf_dir: variant_qc_random_forest
vcf_output_dir: filtered_vcfs  # A timestamp will be added automatically by the script

fam_pedigree: ["Fenland_Axiom_UKB_Sanger_exomeid.fam","Fenland_core_exome_Sanger_exomeid.fam","Fenland_SNP5.0_Sanger_exomeid.fam"]
sex_and_ethnicity_annotation_file: fenland_sex_and_ethnicity.csv
file_id_remap:
pedfile_name: trios.ped

rf_test_interval: chr20

runhash: fef0f446

samples_to_exclude: Birth_Cohorts_Data_Note_ALSPAC_348_samples_removed.txt
samples_rename_map: ""

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 42
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 40
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 36
      dp: 5
      gq: 20
      ab: 0.2
  indel:
    relaxed:
      bin: 62
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 59
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 56
      dp: 10
      gq: 10
      ab: 0.3
