---

#tmp_dir: "hdfs://spark-master:9820/user/ubuntu/hail-tmp"
tmp_dir: "file:///lustre/scratch126/teams/hgi/gz3-fenland/tmp"

# === Root folders
data_root: /lustre/scratch126/teams/hgi/gz3-fenland # Root folder for all input and analysis data
dataset_name: gz3-fenland  # Used in automatically created files and folders

gatk_vcf_header: gatk_vcf_header.txt
gatk_import_lustre_dir:    gatk_vcfs_rmdup


annotation_lustre_dir: annotations
matrixtables_lustre_dir: matrixtables
stats_dir: stats
plots_lustre_dir: plots
resource_dir: resources
training_set_dir: training_sets
var_qc_rf_dir: variant_qc_random_forest
vcf_output_dir: filtered_vcfs  # A timestamp will be added automatically by the script

fam_pedigree: ["Fenland_Axiom_UKB_Sanger_exomeid.fam","Fenland_core_exome_Sanger_exomeid.fam","Fenland_SNP5.0_Sanger_exomeid.fam"]
self_reported_sex: fenland_self_reported_sex.csv
exclude_variations_file: "variants_to_remove.vcf"
fam_id_remap: 7286_pedigree_name_map.csv
pedfile_name: "" # We don't have trios for the Fenland data set
n_pca: 3
kg_dir: 1kg_vcf_nosv # "1kg_vcf" # Filter fr 100genomes VCFS inside `resources`
kg_pop: igsr_samples.tsv # downloaded from https://www.internationalgenome.org/data-portal/sample

rf_test_interval: chr20

runhash: 5278832e # trained on chr20
# runhash: 9370bdf6 # trained on chr1

samples_to_exclude: "Fenland_samples_failed_gtcheck_ids.txt"
samples_rename_map: ""

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 92
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 89
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 83
      dp: 5
      gq: 10
      ab: 0.2
  indel:
    relaxed:
      bin: 72
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 68
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 56
      dp: 5
      gq: 10
      ab: 0.2
