---
gatk_vcf_header: file:///lustre/scratch123/qc/BiB/gatk_vcf_header.txt
gatk_import_lustre_dir: file:///lustre/scratch123/qc/BiB/gatk_vcfs/
load_matrixtables_lustre_dir: /lustre/scratch123/qc/BiB/matrixtables/
#load_matrixtables_lustre_dir: /lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
annotation_lustre_dir: file:///lustre/scratch123/qc/BiB/annotations/
annotation_lustre_dir_local: /lustre/scratch123/qc/BiB/annotations/
matrixtables_lustre_dir: file:///lustre/scratch123/qc/BiB/matrixtables/
#matrixtables_lustre_dir: file:///lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
plots_lustre_dir: file:///lustre/scratch123/qc/BiB/plots/
plots_dir_local: /lustre/scratch123/qc/BiB/plots/
resource_dir: file:///lustre/scratch123/qc/BiB/resources/
resource_dir_local: /lustre/scratch123/qc/BiB/resources/
training_set_dir: file:///lustre/scratch123/qc/BiB/training_sets/
var_qc_rf_dir: file:///lustre/scratch123/qc/BiB/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch123/qc/BiB/filtered_vcfs/

rf_test_interval: chr20

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 92
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 88
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 84
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 68
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 66
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 58
      dp: 5
      gq: 20
      ab: 0.3
