---

general:
  # CVAR tmpdir
  tmp_dir: /lustre/scratch126/mk43/tmp/
  # tmp_dir: hdfs://spark-master:9820/

  # CVAR anndir
  annotation_dir: /lustre/scratch126/dh24_test/qc_test/BiB/annotations/
  
  # CVAR mtdir
  matrixtables_dir: /lustre/scratch126/dh24_test/qc_test/BiB/matrixtables/

  # TODO: document resource_dir
  # TODO: add option to override in `resources` config field
  # TODO: add Jira ticket
  # CVAR resdir
  resource_dir: /lustre/scratch126/dh24_test/qc_test/BiB/resources/

  # CVAR 1kg_resdir
  1kg_resource_dir: /lustre/scratch126/dh24_test/qc_test/BiB/resources/mini_1000G/

  # CVAR pltdir
  plots_dir: /lustre/scratch126/dh24_test/qc_test/BiB/plots/

# --- Step 1.1 --- #
step1:
  gatk_vcf_header_infile:
  gatk_vcf_indir: /lustre/scratch126/WES_QC/control_set_vcfs/control_set_small/
  gatk_mt_outfile: '{mtdir}/gatk_unprocessed.mt'

step2:
  # --- Step 2.1 --- #
  sex_annotation_hard_filters:
    filtered_mt_outfile: '{mtdir}/mt_hard_filters_annotated.mt'
    n_alt_alleles_threshold: 0.001
    defined_gt_frac_threshold: 0.99

  impute_sex:
    sex_ht_outfile: '{anndir}/sex_annotated.sex_check.txt.bgz'
    sex_mt_outfile: '{mtdir}/mt_sex_annotated.mt'
    female_threshold: 0.5
    male_threshold: 0.8
    aaf_threshold: 0.05
    
  sex_inconsistencies:
    # TODO: specify structure of a sex metadata file
    sex_metadata_file: '{resdir}/mlwh_sample_and_sex.txt'
    conflicting_sex_report_file: '{anndir}/conflicting_sex.txt.bgz'
    fstat_outliers_report_file: '{anndir}/sex_annotation_f_stat_outliers.txt.bgz'
    fstat_low: 0.2
    fstat_high: 0.8

  # --- Step 2.2 --- #
  prune:
    pruned_mt_file: '{mtdir}/mt_ldpruned.mt'
    ld_prune_args:
      r2: 0.2
      # bp_window_size:
      # memory_per_core:
      # keep_higher_maf:
      # block_size: 

  # preciously pc_relate
  prune_pc_relate:
    relatedness_ht_file: '{mtdir}/mt_relatedness.ht'
    samples_to_remove_file: '{mtdir}/mt_related_samples_to_remove.ht'
    scores_file: '{mtdir}/mt_pruned.pca_scores.ht'
    pca_components: 3
    pc_relate_args:
      min_individual_maf: 0.05
      block_size: 4096
      min_kinship: 0.05
      statistics: 'kin2'
      # k:
      # include_self_kinship:
    relatedness_column: 'kin'
    relatedness_threshold: 0.125
    
  # previously population_pca
  prune_plot_pca:
    plink_outfile: '{mtdir}/mt_unrelated.plink'

    pca_components: 4
    pca_scores_file: '{mtdir}/mt_pca_scores.ht'
    pca_loadings_file: '{mtdir}/mt_pca_loadings.ht'
    pca_mt_file: '{mtdir}/mt_pca.mt'

    plot_outfile: '{pltdir}/pca.html'
  
  # --- Step 2.3 --- #
  create_1kg_mt:
    indir: '{1kg_resdir}'
    vcfheader: '{1kg_resdir}/header_20201028.txt'
    mt_out_file: '{mtdir}/kg_wes_regions.mt'

  merge_with_1_kg:
    kg_mt_file: '{mtdir}/kg_wes_regions.mt'
    merged_mt_outfile: '{mtdir}/merged_with_1kg'

  annotate_and_filter:
    pops_file: '{resdir}/igsr_samples.tsv'
    call_rate: 0.99
    AF: 0.05
    p_value_hwe: 0.00005
    long_range_ld_file: '{resdir}/long_ld_regions.hg38.bed'
    filtered_mt_outfile: '{mtdir}/merged_with_1kg_filtered.mt'
  
  run_pca:
    pca_scores_outfile: '{mtdir}/pca_scores_after_pruning.ht'
    pca_loadings_outfile: '{mtdir}/pca_loadings_after_pruning.ht'
    pca_evals_outfile: '{mtdir}/pca_evals_after_pruning.txt' # TODO: don't add prefix

  predict_pops:
    pca_scores_file: '{mtdir}/pca_scores_after_pruning.ht'
    gnomad_pc_n_estimators: 100
    gnomad_prop_train: 0.8
    gnomad_min_prob: 0.5
    pop_ht_outfile: '{mtdir}/pop_assignments.ht'
    pop_ht_outtsv: '{mtdir}/pop_assignments.tsv'
  

  # --- Step 2.3 --- #
  # tmp before dh's merge
  pop_pred_pca:
    pca_scores_file: '{mtdir}/pca_scores_after_pruning.ht'
    pca_loadings_file: '{mtdir}/pca_loadings_after_pruning.ht'
    pca_evals_file: '{mtdir}/pca_evals_after_pruning.txt'

  predict_populations:
    pop_ht_file: '{mtdir}/pop_assignments.ht'
    pop_ht_tsv: '{mtdir}/pop_assignments.tsv'

  # --- Step 2.4 --- #

  # annotate_mt
  annotate_with_pop:
    annotated_mt_file: '{mtdir}/gatk_unprocessed_with_pop.mt'

  stratified_sample_qc:
    mt_qc_outfile: '{mtdir}/mt_pops_sampleqc.mt'
    ht_qc_cols_outfile: '{mtdir}/mt_pops_sampleqc.ht'
    qc_filter_file: '{mtdir}/mt_pops_QC_filters.ht'

    min_depth: 20
    min_genotype_quality: 20
    min_vaf: 0.25
    output_text_file: '{anndir}/sample_qc_by_pop.tsv.bgz'
    output_globals_json_file: '{anndir}/sample_qc_by_pop.globals.json'
  
  # --- Step 2.5 --- #

  remove_sample_qc_fails:
    samples_failing_qc_file: '{anndir}/samples_failing_qc.tsv.bgz'
    sample_qc_filtered_mt_file: '{mtdir}/mt_pops_QC_filters_after_sample_qc.mt'
  


# unprocessed below this line

plots_lustre_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/plots/
plots_dir_local: /lustre/scratch126/dh24_test/qc_test/BiB/plots/

training_set_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/training_sets/
var_qc_rf_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch126/dh24_test/qc_test/BiB/filtered_vcfs/

# TODO: this is a redundant field that differs to matrixtables_dir only in prefix
load_matrixtables_lustre_dir: /lustre/scratch126/dh24_test/qc_test/BiB/matrixtables/


rf_test_interval: chr20

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 92
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 88
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 84
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 68
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 66
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 58
      dp: 5
      gq: 20
      ab: 0.3
