---
gatk_vcf_header: file:///lustre/scratch126/teams/hgi/vo3_bib/VCF_header.txt
gatk_import_lustre_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/pre_QC_VCFs/
load_matrixtables_lustre_dir: /lustre/scratch126/teams/hgi/vo3_bib/qc/matrixtables/
#load_matrixtables_lustre_dir: /lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
annotation_lustre_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/annotations/
annotation_lustre_dir_local: /lustre/scratch126/teams/hgi/vo3_bib/qc/annotations/
matrixtables_lustre_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/matrixtables/
#matrixtables_lustre_dir: file:///lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
plots_lustre_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/plots/
plots_dir_local: /lustre/scratch126/teams/hgi/vo3_bib/qc/plots/
resource_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/resources/
resource_dir_local: /lustre/scratch126/teams/hgi/vo3_bib/qc/resources/
training_set_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/training_sets/
var_qc_rf_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/variant_qc_random_forest/
vcf_output_dir: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/filtered_vcfs/


kg_dir: file:///lustre/scratch125/resources/1000g/release/20201028/
kg_vcfheader: file:///lustre/scratch123/projects/gnh_industry/Genes_and_Health_2024_05_55k/qc/header.txt

tmp_dir: file:///lustre/scratch126/teams/hgi/users/vo3/tmp/

metadata_file: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/resources/srs_bib.txt


all_consequences: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/resources/all_consequences.txt
pedigree_file: file:///lustre/scratch126/teams/hgi/vo3_bib/qc/resources/BiB2_trios.txt

giabVCF: file:///lustre/scratch123/projects/gnh_industry/Genes_and_Health_2024_05_55k/qc/resources/HG001_GRCh38_benchmark.interval.illumina.vcf.gz
giab_cq_file: file:///lustre/scratch123/projects/gnh_industry/Genes_and_Health_2024_05_55k/qc/resources/all.interval.illumina.vep.info.txt


rf_test_interval: chr20

#hard filter
hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 91
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 89
      dp: 5
      gq: 10
      ab: 0.2
    stringent:
      bin: 85
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 70
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 68
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 62
      dp: 5
      gq: 20
      ab: 0.3
