---
cromwell_base_dir: /lustre/scratch119/realdata/mdt3/projects/birth_cohort_wes/alspac/gatk/joint_call/cromwell/cromwell-executions/JointCalling/
target_dir: /lustre/scratch123/gz3/gz3/gz3-wes-qc-mcs/gatk_vcfs/
regions:
  chr1_3_dir: 303af8c0-4b7b-4388-98b5-2f552584a8f7
  chr4_8_dir: 5b20ad2f-9f35-4713-b171-a7f8f0b0aebc
  chr9_14_dir: 679738e5-0a41-4196-8b4e-f1e01d80b077
  chr15_Y_dir: 75f0aeda-115f-46c0-bcfe-44344cd6fec9

tmp_dir: "hdfs://spark-master:9820/user/ubuntu/hail-tmp"
#tmp_dir: file:///lustre/scratch123/gz3/tmp

data_root: /lustre/scratch123/gz3/gz3-wes-qc-mcs # Root folder for all input and analysis data
dataset_name: gz3-wes-qc-mcs  # Used in automatically created files and folders

gatk_vcf_header: gatk_vcf_header.txt
gatk_import_lustre_dir: gatk_vcfs
load_matrixtables_lustre_dir: matrixtables  # Writing using direct Python no need the name without file:// prefix
annotation_lustre_dir: annotations
annotation_lustre_dir_local: undefined
matrixtables_lustre_dir: matrixtables
#matrixtables_lustre_dir: file:///lustre/scratch123/qc/matrixtables/mts_for_control_datasets/
stats_dir: stats
plots_lustre_dir: plots
plots_dir_local: plots
resource_dir: resources
resource_dir_local: resources
training_set_dir: training_sets
var_qc_rf_dir: variant_qc_random_forest
vcf_output_dir: filtered_vcfs  # A timestamp will be added automatically by the script
pedfile_name: trios_only.ped

rf_test_interval: chr20

runhash: 0e5d073b

samples_to_exclude: Birth_Cohorts_MCS_458_samples_to_remove.txt
samples_rename_map: "MCS_BIBKIDEX_2_EGA.tsv"

hard_filters:
  missingness: 0.5
  snp:
    relaxed:
      bin: 86
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 84
      dp: 5
      gq: 15
      ab: 0.2
    stringent:
      bin: 82
      dp: 5
      gq: 15
      ab: 0.2
  indel:
    relaxed:
      bin: 64
      dp: 5
      gq: 10
      ab: 0.2
    medium:
      bin: 62
      dp: 5
      gq: 15
      ab: 0.3
    stringent:
      bin: 58
      dp: 10
      gq: 20
      ab: 0.3
