#!/bin/sh

kg_source="ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20220422_3202_phased_SNV_INDEL_SV/"
kg_dir="/lustre/scratch126/teams/hgi/gz3-fenland/resources/1kg_vcf"
kg_dir_no_sv="/lustre/scratch126/teams/hgi/gz3-fenland/resources/1kg_vcf_no_sv"

cd "$kg_dir"
wget -c -r --no-parent --no-directories "$kg_source"



#!/bin/bash
set -e
chr=${1:-$LSB_JOBINDEX}
echo "Processing chr$chr"
vcf_in="1kg_vcf/1kGP_high_coverage_Illumina.chr$chr.filtered.SNV_INDEL_SV_phased_panel.vcf.gz"
vcf_out="1kg_vcf_nosv/chr$chr.nosv.vcf.gz"
bcftools filter -O z -i 'type="snp" | type="indel"' $vcf_in | bcftools annotate --threads 1 -x "INFO/END2" -O z -o $vcf_out
echo "Processing chr$chr done"


bsubrun -q small -n 4 ./vcf_filter_sv X
bsubrun -q small -n 4 -J [1-22] ./vcf_filter_sv
