#!/bin/bash

# This script runs the Python code form the repository on the remote Hail cluster
# It does the following things
#     1. Syncs local repository to the remove cluster
#     2. Substitutes the local Python file path to the corresponding path on the remote cluster
#     3. Starts the detached tmux session
#     4. Runs the Python file in the detached session
#     5. Connects to the session to see the progress
# The running process should continue even if the SSH connection breaks.

set -e
script="${1}"
args="${*:2}"

repo="wes_qc"
local_path="/Users/gz3/programming"
remote_path="/home/ubuntu/temprun"
session_name="HailBatch"

SSH='/usr/bin/ssh'
# Checking whether we are using Teleport to access cluster
if [ "$TELEPORT_PROXY" == "True" ]; then
    SSH="sshteleport"  # Custom script calling ssh via Teleport socks5 proxy
fi
echo "Syncing local repo to Hail cluster ${hail_cluster}"
echo "Sync command ${SSH}"
rsync -avz -e "$SSH" --exclude '.git' --exclude '.idea' --exclude '.snakemake' --exclude '.mypy_cache' "${local_path}/${repo}" "${hail_cluster}:${remote_path}"

echo "Running script ${script} on the Hail cluster ${hail_cluster}"
script_local_path=$( readlink -f "${script}" )
script_repo_path=$( echo "${script_local_path}" | sed "s|[A-z0-9/]*/${repo}/||" )
script_remote_path="${remote_path}/${repo}/${script_repo_path}"
echo "Remote run path changed to ${script_remote_path}"

# Run via tmux session. Should remain even is connection has been closed.
command="./scripts/hlrun_local ${script_remote_path} ${args}"

echo "Creating detached session and running command"
$SSH ${hail_cluster} "tmux new-session -A -s ${session_name} -d"

echo "Sending command ${command}"
command_subs=$(echo $command | sed 's| | Space |g' )
$SSH ${hail_cluster} "tmux send-keys -t ${session_name} cd Space ${remote_path}/${repo} Enter"
$SSH ${hail_cluster} "tmux send-keys -t ${session_name} ${command_subs} Enter"

echo "Attaching to the tmux session"
$SSH -t ${hail_cluster} tmux attach -t "${session_name}"
