name: Sync to analysis repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Make
      run: sudo apt-get install -y make

    - name: Sync
      run: |
        git remote add origin-private https://wtsi-hgi:${{ secrets.DEPLOY_TOKENS }}@github.com/wtsi-hgi/wes-qc-analysis.git || true
        make sync-to-private
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
